server:
  port: 8081
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
spring:
  application:
    name: pizzeria-meal
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    url: jdbc:postgresql://localhost:5432/pizzeria-meal
    name: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: ALWAYS
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
rabbit:
  save-order-queue: save-order-queue