server:
  port: 8083
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
spring:
  application:
    name: pizzeria-mail
  mail:
    host: smtp.gmail.com
    username: mail@mail.com
    password: password
    port: 587
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
        ssl.enable: false
mail:
  to: mail@gmail.com
  from: mail@gmail.com
rabbit:
  send-mail-queue: send-mail-queue